version: "3.7"
services:

## OpenVPN - VPN Service
  openvpn:
    container_name: openvpn
    image: darathor/openvpn
    restart: always
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      pi_net:
        ipv4_address: 172.20.200.40
    ports:
      - "1194:1194"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/docker/openvpn:/etc/openvpn

networks:
  pi_net:
    external:
      name: pi_net

