version: "3.7"
services:

## Adminer - Database Management
  adminer:
    container_name: adminer
    image: dehy/adminer
    restart: always
    networks:
      - traefik_proxy
#    ports:
#     - "80:80"
#    environment:
#      - ADMINER_DEFAULT_SERVER=mariadb
#      - ADMINER_DESIGN=     # https://github.com/vrana/adminer/tree/master/designs
#      - ADMINER_PLUGINS=   # https://github.com/vrana/adminer/tree/master/plugins
    labels:
      - "traefik.enable=true"
      - "traefik.backend=adminer"
      - "traefik.frontend.rule=Host:adminer.$DOMAINNAME"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=adminer.$DOMAINNAME"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.customResponseHeaders: X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.auth.forward.address=http://oauth:4181"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User"
      - "traefik.frontend.auth.forward.trustForwardHeader=true"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
