version: "3.7"
services:

## Baikal - Cal and CardDAV Server
  baikal:
    container_name: baikal
    image: bambucha/baikal
    restart: always
    networks:
      - traefik_proxy
#    ports:
#      - "XXXX:80"
    volumes:
      - ${USERDIR}/docker/baikal:/baikal/Specific
    labels:
      - "traefik.enable=true"
      - "traefik.backend=baikal"
      - "traefik.frontend.rule=Host:baikal.${DOMAINNAME}"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=baikal.${DOMAINNAME}"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.auth.forward.address=http://oauth:4181"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
