version: "3.7"
services:

## Dillinger - Markdown Editor
  dillinger:
    container_name: dillinger
    image: joemccann/dillinger
    restart: always
    networks:
      - traefik_proxy
#    ports:
#     - "9000:9000"
    environment:
      - "BIND_ADDRESS=0.0.0.0"
      - "PORT=9000"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=dillinger"
      - "traefik.frontend.rule=Host:dillinger.${DOMAINNAME}"
      - "traefik.port=9000"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=dillinger.${DOMAINNAME}"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.auth.forward.address=http://oauth:4181"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
