version: "3.7"
services:

## Dokuwiki - Personal Wiki
  dokuwiki:
    container_name: dokuwiki
    image: mprasil/dokuwiki
    restart: always
    networks:
      - traefik_proxy
#    ports:
#      - "XXXX:80"
    volumes:
      - ${USERDIR}/docker/dokuwiki/data:/dokuwiki/data
      - ${USERDIR}/docker/dokuwiki/conf:/dokuwiki/conf
      - dokuwiki_plugins:/dokuwiki/lib/plugins
      - dokuwiki_tpl:/dokuwiki/lib/tpl
      - dokuwiki_logs:/var/log
    labels:
      - "traefik.enable=true"
      - "traefik.backend=dokuwiki"
      - "traefik.frontend.rule=Host:dokuwiki.${DOMAINNAME}"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=dokuwiki.${DOMAINNAME}"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.auth.forward.address=http://oauth:4181"

volumes:
  dokuwiki_logs:
  dokuwiki_plugins:
  dokuwiki_tpl:

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
