version: "3.7"
services:

## Droppy – File Share
  droppy:
    container_name: droppy
    image: silverwind/droppy
    restart: unless-stopped
    networks:
      - traefik_proxy
#    ports:
#      - "8989:8989"
    volumes:
      - ${USERDIR}/docker/droppy:/config
      - ${USERDIR}/dwnloads:/files
    labels:
      - "traefik.enable=true"
      - "traefik.backend=droppy"
      - "traefik.frontend.rule=Host:droppy.${DOMAINNAME}"
      - "traefik.port=8989"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=droppy.${DOMAINNAME}"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.auth.forward.address=http://oauth:4181"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
