version: "3.7"
services:

## Emby Media Server
  emby:
    container_name: emby
    image: emby/embyserver:latest
    restart: always
    devices:
     - /dev/dri:/dev/dri
    networks:
      - traefik_proxy
    ports:
      - "8096:8096"
      - "8920:8920"
    volumes:
      - /mnt/storage/movies:/MOVIES:ro
      - /mnt/storage/tv:/TVSHOWS:ro
      - /mnt/storage/concerts:/CONCERTS:ro
      - /mnt/storage/music/music:/music:ro
      - ${USERDIR}/docker/emby:/config
    environment:
      - UID=${PUID}
      - GID=${PGID}
      - GIDLIST=44
    labels:
      - "traefik.enable=true"
      - "traefik.backend=emby"
      - "traefik.frontend.rule=Host:emby.${DOMAINNAME}"
      - "traefik.port=8096"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=emby.${DOMAINNAME}"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.customResponseHeaders: X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
      - "traefik.frontend.headers.frameDeny=true"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
