version: "3.7"
services:

## Firefox
  firefox:
    container_name: firefox
    image: jlesage/firefox
    restart: unless-stopped
    networks:
      - traefik_proxy
#    ports:
#      - "5800:5800"
    volumes:
      - ${USERDIR}/docker/firefox:/config
      - /dev/shm:/dev/shm
#      - /etc/timezone:/etc/timezone:ro
    environment:
      - USER_ID=${PUID}
      - GROUP_ID=${PGID}
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=firefox"
      - "traefik.frontend.rule=Host:firefox.${DOMAINNAME}"
      - "traefik.port=5800"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=firefox.${DOMAINNAME}"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
