version: "3.7"
services:

## Gitea - Selfhosted Git Service
  # To generate SECRET_KEY:
  # docker exec -it gitea gitea generate secret SECRET_KEY
  gitea:
    container_name: gitea
    image: gitea/gitea
    restart: always
    networks:
      - traefik_proxy
#    ports:
#      - '3000:3000'
#      - '2222:22'
    volumes:
      - ${USERDIR}/docker/gitea:/data
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=mariadb:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=${MYSQL_PASSWORD}
      - RUN_MODE=prod
#      - INSTALL_LOCK=true # Disallow access to the install page. Enable after first sign in
#      - SECRET_KEY=”” # Global secret key. This should be changed. If this has a value and INSTALL_LOCK is empty, INSTALL_LOCK will automatically set to true.
#      - DISABLE_REGISTRATION=false # Disable registration, after which only admin can create accounts for users.
    labels:
      - "traefik.enable=true"
      - "traefik.backend=gitea"
      - "traefik.frontend.rule=Host:gitea.${DOMAINNAME}"
      - "traefik.port=3000"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=gitea.${DOMAINNAME}"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.customResponseHeaders: X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
      - "traefik.frontend.headers.frameDeny=true"
#      - "traefik.frontend.auth.forward.address=http://oauth:4181"
#      - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User"
#      - "traefik.frontend.auth.forward.trustForwardHeader=true"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
