version: "3.7"
services:

## Healthchecks - Cron Monitor
  # Need to manually add "ALLOWED_HOSTS, SECRET_KEY, and REGISTRATION_OPEN" to bottom of local_settings file
  # Additional config settings here:
  # https://github.com/healthchecks/healthchecks
  healthchecks:
    container_name: healthchecks
    image: linuxserver/healthchecks
    restart: always
    networks:
      - traefik_proxy
    ports:
      - "8000:8000"
    volumes:
      - ${USERDIR}/docker/healthchecks:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
#      - TZ=${TZ}
      - SITE_ROOT=https://healthchecks.${DOMAINNAME}
      - SITE_NAME=healthchecks
      - DEFAULT_FROM_EMAIL=${MY_EMAIL}
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=${MY_EMAIL}
      - EMAIL_HOST_PASSWORD=${MY_PASSWORD}
      - EMAIL_USE_TLS=True
##      - ALLOWED_HOSTS = ["*"] # healthchecks.${DOMAINNAME},https://healthchecks.${DOMAINNAME}
##      - SECRET_KEY = "${SECRET_KEY}"
##      - REGISTRATION_OPEN = "True"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=healthchecks"
      - "traefik.frontend.rule=Host:healthchecks.${DOMAINNAME}"
      - "traefik.port=8000"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=healthchecks.${DOMAINNAME}"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.customResponseHeaders: X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
      - "traefik.frontend.headers.frameDeny=true"
#      - "traefik.frontend.auth.forward.address=http://oauth:4181"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
