version: "3.7"
services:

## HomeDash - Homepage
  # SALT is a random string of characters:
  # openssl rand -base64 48
  homedash:
    container_name: homedash
    image: gonzague/homedash
    restart: always
    networks:
      - traefik_proxy
#    ports:
#      - "4567:4567"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/homedash:/data
    environment:
      - UID=${PUID}
      - GID=${PGID}
      - SALT=${SALT}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=homedash"
      - "traefik.frontend.rule=Host:homedash.${DOMAINNAME}"
      - "traefik.port=4567"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=homedash.${DOMAINNAME}"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.auth.forward.address=http://oauth:4181"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
