version: "3.7"
services:

## Jellyfin - Media Server
  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin
    restart: always
    devices:
     - /dev/dri:/dev/dri
    networks:
      - traefik_proxy
    ports:
      - "8097:8096"
      - "8921:8920"
    volumes:
      - /mnt/storage/movies:/MOVIES:ro
      - /mnt/storage/tv:/TVSHOWS:ro
      - /mnt/storage/concerts:/CONCERTS:ro
      - ${USERDIR}/docker/jellyfin:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    labels:
      - "traefik.enable=true"
      - "traefik.backend=jellyfin"
      - "traefik.frontend.rule=Host:jellyfin.${DOMAINNAME}"
      - "traefik.port=8096"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=jellyfin.${DOMAINNAME}"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.customResponseHeaders: X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
      - "traefik.frontend.headers.frameDeny=true"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
