version: "3.7"
services:

## I changed the sqlite db to mysql. First create the database:
# docker exec -it mariadb mysql -uroot -p
# CREATE DATABASE kanboard CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
# CREATE USER 'kanboard' IDENTIFIED BY 'CHANGEME';
# GRANT ALTER, CREATE, DELETE, DROP, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON kanboard.* TO 'kanboard'@'kanboard.traefik_proxy'IDENTIFIED BY 'CHANGEME';
# FLUSH PRIVILEGES;
# exit

## Create custom config:
  # mkdir ${USERDIR}/docker/kanboard
  # docker run --rm --entrypoint cat kanboard/kanboard /var/www/app/config.default.php > ${USERDIR}/docker/kanboard/config.php

## Change the following parameters in the
  # ('DB_DRIVER', 'mysql')
  # ('DB_USERNAME', 'kanboard')
  # ('DB_PASSWORD', 'CHANGEME')
  # ('DB_HOSTNAME', 'mariadb')
  # ('DB_PORT', '3306')

## Start kanboard

## Kanboard - Project Management Software
  # Login: admin / admin
  kanboard:
    container_name: kanboard
    image: kanboard/kanboard
    restart: always
    external_links:
      - mariadb
    networks:
      - traefik_proxy
#    ports:
#      - "80:80"
#      - "443:443"
    volumes:
      - kanboard_plugins:/var/www/app/plugins
      - kanboard_ssl:/etc/nginx/ssl
      - ${USERDIR}/docker/kanboard/config.php:/var/www/app/config.php
#    environment:
#      - REVERSE_PROXY_DEFAULT_DOMAIN=http://kanboard.${DOMAINNAME}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=kanboard"
      - "traefik.frontend.rule=Host:kanboard.${DOMAINNAME}"
      - "traefik.port=443"
      - "traefik.protocol=https"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=kanboard.${DOMAINNAME}"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.auth.forward.address=http://oauth:4181"

volumes:
  kanboard_plugins:
  kanboard_ssl:

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
