version: "3.7"
services:

## KeyCloak

  # docker exec -it mariadb mysql -uroot -p
  # CREATE DATABASE keycloak CHARACTER SET = utf8 COLLATE = utf8_general_ci;
  # GRANT ALL PRIVILEGES ON keycloak.* TO 'keycloak'@'keycloak.traefik_proxy'IDENTIFIED BY '<password>';
  # FLUSH PRIVILEGES;
  # exit

  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    restart: always
    networks:
      - traefik_proxy
    ports:
      - '8111:8080'
    environment:
      - DB_VENDOR=mysql
      - DB_ADDR=mariadb
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=${MY_PASSWORD}
#      - KEYCLOAK_USER= ## Commented out after initial setup
#      - KEYCLOAK_PASSWORD= ## Commented out after initial setup
#      - PROXY_ADDRESS_FORWARDING=true
#      - KEYCLOAK_HOSTNAME=keycloak.${DOMAINNAME}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=keycloak"
      - "traefik.frontend.rule=Host:keycloak.${DOMAINNAME}"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
