services:

## LetsEncrypt - Certificates
  # Generate .htpasswd files
  # If you wish to hide your site from search engine crawlers, you may find it useful to add this configuration line to your site config, within the server block, above the line where ssl.conf is included add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";
  ## docker exec -it letsencrypt htpasswd -c /config/nginx/.htpasswd
  letsencrypt:
    container_name: letsencrypt
    image: linuxserver/letsencrypt
    restart: always
    cap_add:
      - NET_ADMIN
    networks:
      - traefik_proxy
#    ports:
#      - "80:80"
#      - "443:443"
    volumes:
      - ${USERDIR}/docker/letsencrypt:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${DOMAINNAME}
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - EMAIL=$MY_EMAIL
      - DHLEVEL=2048
      - STAGING=false #true
    labels:
      - "traefik.enable=true"
      - "traefik.port=443"
      - "traefik.docker.network=traefik_proxy"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
