version: "3.7"
services:

## Mailu - Mail Server
  # mkdir ${USERDIR}/docker/mailu
  # Run setup utility: https://setup.mailu.io/
  # docker run --rm --entrypoint cat tomsquest/docker-radicale /config/config > ${USERDIR}/docker/radicale/config
  mailu:
    container_name: mailu
    image: mailu/radicale
    restart: always
    networks:
      - traefik_proxy
#    ports:
#      - "5232:5232"
    volumes:
      - ${USERDIR}/docker/mailu/data:/data
      - ${USERDIR}/docker/mailu/config:/config/config
    environment:
      - UID=${PUID}
      - GID=${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=mailu"
      - "traefik.frontend.rule=Host:mailu.${DOMAINNAME}"
      - "traefik.port=5232"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.auth.forward.address=http://oauth:4181"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
