version: "3.7"
services:

## Mariadb – Database Server

  ## Suggested procedure to create new databases:
  ## Replace <these values>
    # docker exec -it mariadb mysql -uroot -p$MYSQL_ROOT_PASSWORD
    # CREATE DATABASE <database name> CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
    # GRANT ALL PRIVILEGES ON <database name>.* TO '<user>'@'<container>.traefik_proxy' IDENTIFIED BY '<password>';
    # FLUSH PRIVILEGES;
    # exit

  ## Some resources for why these commands are chosen:
  ## utf8mb4 is the most universal and up to date character set allowing for emojis among other benefits
  ## utf8mb4_unicode_ci is the "standard" database type while general_ci is a simplified version which tried to improve speed before modern computing. I believe there is little to no benefit to use the simpler version.
  ## https://docs.nextcloud.com/server/16/admin_manual/configuration_database/mysql_4byte_support.html
  ## For a complete list of available options: docker run -it --rm mariadb --verbose --help
  ## Check your global database variables, for example character_set_server with:
    # docker exec -it mariadb mysql -uroot -p$MYSQL_ROOT_PASSWORD
    # SHOW VARIABLES LIKE 'character_set_server';
    # SHOW VARIABLES LIKE '%server%';
    # exit

  ## Delete the initial test and default databases and secure MySQL:
    # docker exec -it mariadb /usr/bin/mysql_secure_installation

  mariadb:
    container_name: mariadb
    image: mariadb:10.4
    restart: always
    networks:
      - traefik_proxy
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-file-format=Barracuda
      --innodb-file-per-table=1
#    ports:
#      - "3306:3306"
    volumes:
      - $USERDIR/docker/mariadb:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD

## phpMyAdmin - WebUI for MariaDB

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - mariadb
    networks:
      - traefik_proxy
#    ports:
#      - "80:80"
    environment:
#      - PMA_ARBITRARY=1 # Allows you to enter a database server hostname on login form
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_ABSOLUTE_URI=https://phpmyadmin.${DOMAINNAME}/
    labels:
      - "traefik.enable=true"
      - "traefik.backend=phpmyadmin"
      - "traefik.frontend.rule=Host:phpmyadmin.${DOMAINNAME}"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=phpmyadmin.${DOMAINNAME}"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.headers.customResponseHeaders: X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
      - "traefik.frontend.auth.forward.address=http://oauth:4181"
      - "traefik.frontend.auth.forward.trustForwardHeader=true"
      - "traefik.frontend.auth.headerField=X-Forwarded-User"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
