version: "3.7"
services:

## mStream - Music Server
  mstream:
    container_name: mstream
    image: rdfriedl/mstream
    restart: always
    networks:
      - traefik_proxy
#    ports:
#      - "80:80"
    volumes:
      - ${USERDIR}/Music:/music
      - /etc/timezone:/etc/timezone:ro
    environment:
      - USER=$MY_USERNAME
      - PASSWORD=$MY_PASSWORD
    labels:
      - "traefik.enable=true"
      - "traefik.backend=mstream"
      - "traefik.frontend.rule=Host:mstream.${DOMAINNAME}"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=mstream.${DOMAINNAME}"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.customFrameOptionsValue=SAMEORIGIN"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
