version: "3.7"
services:

## Shaarli
  shaarli:
    container_name: shaarli
    image: shaarli/shaarli:master
    restart: always
    networks:
      - traefik_proxy
#    ports:
#      - "80:80"
    volumes:
      - shaarli-data:/var/www/shaarli/data
      - shaarli-cache:/var/www/shaarli/cache
    labels:
      - "traefik.enable=true"
      - "traefik.backend=shaarli"
      - "traefik.frontend.rule=Host:shaarli.${DOMAINNAME}"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=shaarli.${DOMAINNAME}"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.auth.forward.address=http://oauth:4181"

volumes:
  shaarli-data:
  shaarli-cache:

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
