version: "3.7"
services:

## Soulseek - P2P Media Service
  soulseek:
    container_name: soulseek
    image: realies/soulseek
    restart: always
    network_mode: "container:qbittorrent"
#    networks:
#      - traefik_proxy
#    ports:
#      - "6080:6080"
    volumes:
      - soulseekdata:/root
      - /mnt/storage/music/to_be_tagged:/root/Soulseek Downloads
      - /mnt/storage/music/music:/Music
      - /etc/timezone:/etc/timezone:ro
    environment:
      - resolution=1280x720
    labels:
      - "traefik.enable=true"
      - "traefik.backend=soulseek"
      - "traefik.frontend.rule=Host:soulseek.${DOMAINNAME}"
      - "traefik.port=6080"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=soulseek.${DOMAINNAME}"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.customResponseHeaders: X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
      - "traefik.frontend.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.frontend.auth.forward.address=http://oauth:4181"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User"
      - "traefik.frontend.auth.forward.trustForwardHeader=true"

volumes:
  soulseekdata:

#networks:
#  traefik_proxy:
#    external:
#      name: traefik_proxy
