version: "3.7"
services:

## StandardFile - File Server for Standard Notes
  # Requires a MySQL database. Create with:
  # docker exec -it mariadb mysql -uroot -p
  # CREATE DATABASE standardnotes CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci;
  # GRANT ALL PRIVILEGES ON standardnotes.* TO 'standardnotes'@'standardfile.traefik_proxy'IDENTIFIED BY '<password>';
  # FLUSH PRIVILEGES;
  # exit
  standardfile:
    container_name: standardfile
    image: dryusdan/standardfile
    restart: always
    networks:
      - traefik_proxy
#    ports:
#      - "3000:3000"
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=standardnotes
      - DB_USERNAME=standardnotes
      - DB_PASSWORD=${MY_PASSWORD}
      - RAILS_ENV=production
      - SECRET_KEY_BASE=use "bundle exec rake secret"
      - RAILS_SERVE_STATIC_FILES=true
      - SALT_PSEUDO_NONCE=use "bundle exec rake secret"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=standardfile"
      - "traefik.frontend.rule=Host:standardfile.${DOMAINNAME}"
      - "traefik.port=3000"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=standardfile.${DOMAINNAME}"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

## StandardNotes - Notes App
  # When registering enter standardfile address under advanced settings (https://standardfile.${DOMAINNAME})
  standardnotes:
    container_name: standardnotes
    image: dryusdan/standardnotes
    restart: always
    networks:
      - traefik_proxy
#    ports:
#      - "3000:3000"
    environment:
      - config.assets.digest=true
    labels:
      - "traefik.enable=true"
      - "traefik.backend=standardnotes"
      - "traefik.frontend.rule=Host:standardnotes.${DOMAINNAME}"
      - "traefik.port=3000"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=standardnotes.${DOMAINNAME}"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.auth.forward.address=http://oauth:4181"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
