version: "3.7"
services:

## Transmission with VPN – Bittorrent Downloader
  transmission:
    container_name: transmission
    image: haugene/transmission-openvpn
    restart: always
    networks:
      traefik_proxy:
        ipv4_address: 192.168.1.243
#      - traefik_proxy
    ports:
      - "9091:9091"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 192.168.1.3
#      - 1.1.1.1
#      - 1.0.0.1
    volumes:
      - ${USERDIR}/dwnloads/transmission/completed:/data/completed
      - ${USERDIR}/dwnloads/transmission/incomplete:/data/incomplete
      - ${USERDIR}/dwnloads/transmission/watch:/data/watch
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/transmission:/data
      - ${USERDIR}/docker/transmission/resolv.conf:/etc/resolv.conf
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_USERNAME=${PIA_USER}
      - OPENVPN_PASSWORD=${PIA_PASS}
      - WEBPROXY_ENABLED=false
      - OPENVPN_CONFIG=CA\ Toronto
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --auth-nocache
      - TRANSMISSION_RPC_USERNAME=${MY_USERNAME}
      - TRANSMISSION_RPC_PASSWORD=${MY_PASSWORD}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.1.1,192.168.*.*"
      - TRANSMISSION_UMASK=002
      - LOCAL_NETWORK=192.168.1.0/24
      - ENABLE_UFW=true
      - UFW_ALLOW_GW_NET=true
      - CREATE_TUN_DEVICE=true
    labels:
      - "traefik.enable=true"
      - "traefik.backend=transmission"
      - "traefik.frontend.rule=Host:transmission.${DOMAINNAME}"
      - "traefik.port=9091"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=transmission.${DOMAINNAME}"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.customResponseHeaders: X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.auth.forward.address=http://oauth:4181"
      - "traefik.frontend.auth.forward.trustForwardHeader=true"
      - "traefik.frontend.auth.headerField=X-Forwarded-User"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
