version: "3.7"
services:

## Wetty - SSH over the web
  wetty:
    container_name: wetty
    image: svenihoney/wetty
    restart: always
    networks:
      - traefik_proxy
#    ports:
#     - "3000:3000"
#    volumes:
#      - ${USERDIR}/.ssh/id_rsa:/root/ssh/id_rsa
    environment:
      - VIRTUAL_HOST=wetty.${DOMAINNAME}
      - VIRTUAL_PORT=3000
      - REMOTE_SSH_SERVER=192.168.1.13
      - REMOTE_SSH_PORT=22
      - REMOTE_SSH_USER=${MY_USERNAME}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=wetty"
      - "traefik.frontend.rule=Host:wetty.${DOMAINNAME}"
      - "traefik.port=3000"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=wetty.${DOMAINNAME}"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.customResponseHeaders: X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.auth.forward.address=http://oauth:4181"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User"
      - "traefik.frontend.auth.forward.trustForwardHeader=true"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
